import { z } from 'zod';
declare const ChildNodeDbOutputSchema: z.ZodObject<z.extendShape<{
    id: z.ZodString;
    parentNode: z.ZodNullable<z.ZodString>;
    draggable: z.ZodBoolean;
    type: z.ZodNullable<z.ZodString>;
    style: z.ZodNullable<z.ZodString>;
    className: z.ZodNullable<z.ZodString>;
    targetPosition: z.ZodNullable<z.ZodString>;
    sourcePosition: z.ZodNullable<z.ZodString>;
    hidden: z.ZodNullable<z.ZodBoolean>;
    selected: z.ZodNullable<z.ZodBoolean>;
    dragging: z.ZodNullable<z.ZodBoolean>;
    selectable: z.ZodNullable<z.ZodBoolean>;
    connectable: z.ZodNullable<z.ZodBoolean>;
    deletable: z.ZodNullable<z.ZodBoolean>;
    focusable: z.ZodNullable<z.ZodBoolean>;
    dragHandle: z.ZodNullable<z.ZodString>;
    width: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    height: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    zIndex: z.ZodNullable<z.ZodNumber>;
    extent: z.ZodNullable<z.ZodString>;
    expandParent: z.ZodNullable<z.ZodBoolean>;
    positionAbsolute: z.ZodNullable<z.ZodString>;
    ariaLabel: z.ZodNullable<z.ZodString>;
}, {
    data: z.ZodString;
    position: z.ZodString;
    versionId: z.ZodNumber;
    internReferenceId: z.ZodString;
    leadloversId: z.ZodNullable<z.ZodNumber>;
    sourceEdges: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        source: z.ZodString;
        target: z.ZodString;
        markerStart: z.ZodString;
        markerEnd: z.ZodString;
        type: z.ZodNullable<z.ZodString>;
        sourceHandle: z.ZodNullable<z.ZodString>;
        targetHandle: z.ZodNullable<z.ZodString>;
        label: z.ZodNullable<z.ZodString>;
        labelStyle: z.ZodNullable<z.ZodString>;
        labelShowBg: z.ZodNullable<z.ZodBoolean>;
        labelBgStyle: z.ZodNullable<z.ZodString>;
        labelBgPadding: z.ZodNullable<z.ZodString>;
        labelBgBorderRadius: z.ZodNullable<z.ZodNumber>;
        style: z.ZodNullable<z.ZodString>;
        animated: z.ZodNullable<z.ZodBoolean>;
        hidden: z.ZodNullable<z.ZodBoolean>;
        deletable: z.ZodNullable<z.ZodBoolean>;
        focusable: z.ZodNullable<z.ZodBoolean>;
        data: z.ZodNullable<z.ZodString>;
        className: z.ZodNullable<z.ZodString>;
        sourceNode: z.ZodNullable<z.ZodString>;
        targetNode: z.ZodNullable<z.ZodString>;
        selected: z.ZodNullable<z.ZodBoolean>;
        zIndex: z.ZodNullable<z.ZodNumber>;
        ariaLabel: z.ZodNullable<z.ZodString>;
        interactionWidth: z.ZodNullable<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }, {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }>, "many">>;
    targetEdges: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        source: z.ZodString;
        target: z.ZodString;
        markerStart: z.ZodString;
        markerEnd: z.ZodString;
        type: z.ZodNullable<z.ZodString>;
        sourceHandle: z.ZodNullable<z.ZodString>;
        targetHandle: z.ZodNullable<z.ZodString>;
        label: z.ZodNullable<z.ZodString>;
        labelStyle: z.ZodNullable<z.ZodString>;
        labelShowBg: z.ZodNullable<z.ZodBoolean>;
        labelBgStyle: z.ZodNullable<z.ZodString>;
        labelBgPadding: z.ZodNullable<z.ZodString>;
        labelBgBorderRadius: z.ZodNullable<z.ZodNumber>;
        style: z.ZodNullable<z.ZodString>;
        animated: z.ZodNullable<z.ZodBoolean>;
        hidden: z.ZodNullable<z.ZodBoolean>;
        deletable: z.ZodNullable<z.ZodBoolean>;
        focusable: z.ZodNullable<z.ZodBoolean>;
        data: z.ZodNullable<z.ZodString>;
        className: z.ZodNullable<z.ZodString>;
        sourceNode: z.ZodNullable<z.ZodString>;
        targetNode: z.ZodNullable<z.ZodString>;
        selected: z.ZodNullable<z.ZodBoolean>;
        zIndex: z.ZodNullable<z.ZodNumber>;
        ariaLabel: z.ZodNullable<z.ZodString>;
        interactionWidth: z.ZodNullable<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }, {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }>, "many">>;
}>, "strip", z.ZodTypeAny, {
    height?: number | null | undefined;
    width?: number | null | undefined;
    sourceEdges?: {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }[] | undefined;
    targetEdges?: {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }[] | undefined;
    data: string;
    type: string | null;
    style: string | null;
    hidden: boolean | null;
    deletable: boolean | null;
    focusable: boolean | null;
    className: string | null;
    selected: boolean | null;
    zIndex: number | null;
    ariaLabel: string | null;
    id: string;
    internReferenceId: string;
    versionId: number;
    leadloversId: number | null;
    parentNode: string | null;
    position: string;
    draggable: boolean;
    targetPosition: string | null;
    sourcePosition: string | null;
    dragging: boolean | null;
    selectable: boolean | null;
    connectable: boolean | null;
    dragHandle: string | null;
    extent: string | null;
    expandParent: boolean | null;
    positionAbsolute: string | null;
}, {
    height?: number | null | undefined;
    width?: number | null | undefined;
    sourceEdges?: {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }[] | undefined;
    targetEdges?: {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }[] | undefined;
    data: string;
    type: string | null;
    style: string | null;
    hidden: boolean | null;
    deletable: boolean | null;
    focusable: boolean | null;
    className: string | null;
    selected: boolean | null;
    zIndex: number | null;
    ariaLabel: string | null;
    id: string;
    internReferenceId: string;
    versionId: number;
    leadloversId: number | null;
    parentNode: string | null;
    position: string;
    draggable: boolean;
    targetPosition: string | null;
    sourcePosition: string | null;
    dragging: boolean | null;
    selectable: boolean | null;
    connectable: boolean | null;
    dragHandle: string | null;
    extent: string | null;
    expandParent: boolean | null;
    positionAbsolute: string | null;
}>;
export declare const NodeDbOutputSchema: z.ZodObject<z.extendShape<{
    id: z.ZodString;
    parentNode: z.ZodNullable<z.ZodString>;
    draggable: z.ZodBoolean;
    type: z.ZodNullable<z.ZodString>;
    style: z.ZodNullable<z.ZodString>;
    className: z.ZodNullable<z.ZodString>;
    targetPosition: z.ZodNullable<z.ZodString>;
    sourcePosition: z.ZodNullable<z.ZodString>;
    hidden: z.ZodNullable<z.ZodBoolean>;
    selected: z.ZodNullable<z.ZodBoolean>;
    dragging: z.ZodNullable<z.ZodBoolean>;
    selectable: z.ZodNullable<z.ZodBoolean>;
    connectable: z.ZodNullable<z.ZodBoolean>;
    deletable: z.ZodNullable<z.ZodBoolean>;
    focusable: z.ZodNullable<z.ZodBoolean>;
    dragHandle: z.ZodNullable<z.ZodString>;
    width: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    height: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    zIndex: z.ZodNullable<z.ZodNumber>;
    extent: z.ZodNullable<z.ZodString>;
    expandParent: z.ZodNullable<z.ZodBoolean>;
    positionAbsolute: z.ZodNullable<z.ZodString>;
    ariaLabel: z.ZodNullable<z.ZodString>;
}, {
    data: z.ZodString;
    position: z.ZodString;
    versionId: z.ZodNumber;
    internReferenceId: z.ZodString;
    leadloversId: z.ZodNullable<z.ZodNumber>;
    childNodes: z.ZodOptional<z.ZodArray<z.ZodObject<z.extendShape<{
        id: z.ZodString;
        parentNode: z.ZodNullable<z.ZodString>;
        draggable: z.ZodBoolean;
        type: z.ZodNullable<z.ZodString>;
        style: z.ZodNullable<z.ZodString>;
        className: z.ZodNullable<z.ZodString>;
        targetPosition: z.ZodNullable<z.ZodString>;
        sourcePosition: z.ZodNullable<z.ZodString>;
        hidden: z.ZodNullable<z.ZodBoolean>;
        selected: z.ZodNullable<z.ZodBoolean>;
        dragging: z.ZodNullable<z.ZodBoolean>;
        selectable: z.ZodNullable<z.ZodBoolean>;
        connectable: z.ZodNullable<z.ZodBoolean>;
        deletable: z.ZodNullable<z.ZodBoolean>;
        focusable: z.ZodNullable<z.ZodBoolean>;
        dragHandle: z.ZodNullable<z.ZodString>;
        width: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
        height: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
        zIndex: z.ZodNullable<z.ZodNumber>;
        extent: z.ZodNullable<z.ZodString>;
        expandParent: z.ZodNullable<z.ZodBoolean>;
        positionAbsolute: z.ZodNullable<z.ZodString>;
        ariaLabel: z.ZodNullable<z.ZodString>;
    }, {
        data: z.ZodString;
        position: z.ZodString;
        versionId: z.ZodNumber;
        internReferenceId: z.ZodString;
        leadloversId: z.ZodNullable<z.ZodNumber>;
        sourceEdges: z.ZodOptional<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            source: z.ZodString;
            target: z.ZodString;
            markerStart: z.ZodString;
            markerEnd: z.ZodString;
            type: z.ZodNullable<z.ZodString>;
            sourceHandle: z.ZodNullable<z.ZodString>;
            targetHandle: z.ZodNullable<z.ZodString>;
            label: z.ZodNullable<z.ZodString>;
            labelStyle: z.ZodNullable<z.ZodString>;
            labelShowBg: z.ZodNullable<z.ZodBoolean>;
            labelBgStyle: z.ZodNullable<z.ZodString>;
            labelBgPadding: z.ZodNullable<z.ZodString>;
            labelBgBorderRadius: z.ZodNullable<z.ZodNumber>;
            style: z.ZodNullable<z.ZodString>;
            animated: z.ZodNullable<z.ZodBoolean>;
            hidden: z.ZodNullable<z.ZodBoolean>;
            deletable: z.ZodNullable<z.ZodBoolean>;
            focusable: z.ZodNullable<z.ZodBoolean>;
            data: z.ZodNullable<z.ZodString>;
            className: z.ZodNullable<z.ZodString>;
            sourceNode: z.ZodNullable<z.ZodString>;
            targetNode: z.ZodNullable<z.ZodString>;
            selected: z.ZodNullable<z.ZodBoolean>;
            zIndex: z.ZodNullable<z.ZodNumber>;
            ariaLabel: z.ZodNullable<z.ZodString>;
            interactionWidth: z.ZodNullable<z.ZodNumber>;
        }, "strip", z.ZodTypeAny, {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }, {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }>, "many">>;
        targetEdges: z.ZodOptional<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            source: z.ZodString;
            target: z.ZodString;
            markerStart: z.ZodString;
            markerEnd: z.ZodString;
            type: z.ZodNullable<z.ZodString>;
            sourceHandle: z.ZodNullable<z.ZodString>;
            targetHandle: z.ZodNullable<z.ZodString>;
            label: z.ZodNullable<z.ZodString>;
            labelStyle: z.ZodNullable<z.ZodString>;
            labelShowBg: z.ZodNullable<z.ZodBoolean>;
            labelBgStyle: z.ZodNullable<z.ZodString>;
            labelBgPadding: z.ZodNullable<z.ZodString>;
            labelBgBorderRadius: z.ZodNullable<z.ZodNumber>;
            style: z.ZodNullable<z.ZodString>;
            animated: z.ZodNullable<z.ZodBoolean>;
            hidden: z.ZodNullable<z.ZodBoolean>;
            deletable: z.ZodNullable<z.ZodBoolean>;
            focusable: z.ZodNullable<z.ZodBoolean>;
            data: z.ZodNullable<z.ZodString>;
            className: z.ZodNullable<z.ZodString>;
            sourceNode: z.ZodNullable<z.ZodString>;
            targetNode: z.ZodNullable<z.ZodString>;
            selected: z.ZodNullable<z.ZodBoolean>;
            zIndex: z.ZodNullable<z.ZodNumber>;
            ariaLabel: z.ZodNullable<z.ZodString>;
            interactionWidth: z.ZodNullable<z.ZodNumber>;
        }, "strip", z.ZodTypeAny, {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }, {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }>, "many">>;
    }>, "strip", z.ZodTypeAny, {
        height?: number | null | undefined;
        width?: number | null | undefined;
        sourceEdges?: {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }[] | undefined;
        targetEdges?: {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }[] | undefined;
        data: string;
        type: string | null;
        style: string | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        id: string;
        internReferenceId: string;
        versionId: number;
        leadloversId: number | null;
        parentNode: string | null;
        position: string;
        draggable: boolean;
        targetPosition: string | null;
        sourcePosition: string | null;
        dragging: boolean | null;
        selectable: boolean | null;
        connectable: boolean | null;
        dragHandle: string | null;
        extent: string | null;
        expandParent: boolean | null;
        positionAbsolute: string | null;
    }, {
        height?: number | null | undefined;
        width?: number | null | undefined;
        sourceEdges?: {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }[] | undefined;
        targetEdges?: {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }[] | undefined;
        data: string;
        type: string | null;
        style: string | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        id: string;
        internReferenceId: string;
        versionId: number;
        leadloversId: number | null;
        parentNode: string | null;
        position: string;
        draggable: boolean;
        targetPosition: string | null;
        sourcePosition: string | null;
        dragging: boolean | null;
        selectable: boolean | null;
        connectable: boolean | null;
        dragHandle: string | null;
        extent: string | null;
        expandParent: boolean | null;
        positionAbsolute: string | null;
    }>, "many">>;
    edges: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        source: z.ZodString;
        target: z.ZodString;
        markerStart: z.ZodString;
        markerEnd: z.ZodString;
        type: z.ZodNullable<z.ZodString>;
        sourceHandle: z.ZodNullable<z.ZodString>;
        targetHandle: z.ZodNullable<z.ZodString>;
        label: z.ZodNullable<z.ZodString>;
        labelStyle: z.ZodNullable<z.ZodString>;
        labelShowBg: z.ZodNullable<z.ZodBoolean>;
        labelBgStyle: z.ZodNullable<z.ZodString>;
        labelBgPadding: z.ZodNullable<z.ZodString>;
        labelBgBorderRadius: z.ZodNullable<z.ZodNumber>;
        style: z.ZodNullable<z.ZodString>;
        animated: z.ZodNullable<z.ZodBoolean>;
        hidden: z.ZodNullable<z.ZodBoolean>;
        deletable: z.ZodNullable<z.ZodBoolean>;
        focusable: z.ZodNullable<z.ZodBoolean>;
        data: z.ZodNullable<z.ZodString>;
        className: z.ZodNullable<z.ZodString>;
        sourceNode: z.ZodNullable<z.ZodString>;
        targetNode: z.ZodNullable<z.ZodString>;
        selected: z.ZodNullable<z.ZodBoolean>;
        zIndex: z.ZodNullable<z.ZodNumber>;
        ariaLabel: z.ZodNullable<z.ZodString>;
        interactionWidth: z.ZodNullable<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }, {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }>, "many">>;
}>, "strip", z.ZodTypeAny, {
    height?: number | null | undefined;
    width?: number | null | undefined;
    childNodes?: {
        height?: number | null | undefined;
        width?: number | null | undefined;
        sourceEdges?: {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }[] | undefined;
        targetEdges?: {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }[] | undefined;
        data: string;
        type: string | null;
        style: string | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        id: string;
        internReferenceId: string;
        versionId: number;
        leadloversId: number | null;
        parentNode: string | null;
        position: string;
        draggable: boolean;
        targetPosition: string | null;
        sourcePosition: string | null;
        dragging: boolean | null;
        selectable: boolean | null;
        connectable: boolean | null;
        dragHandle: string | null;
        extent: string | null;
        expandParent: boolean | null;
        positionAbsolute: string | null;
    }[] | undefined;
    edges?: {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }[] | undefined;
    data: string;
    type: string | null;
    style: string | null;
    hidden: boolean | null;
    deletable: boolean | null;
    focusable: boolean | null;
    className: string | null;
    selected: boolean | null;
    zIndex: number | null;
    ariaLabel: string | null;
    id: string;
    internReferenceId: string;
    versionId: number;
    leadloversId: number | null;
    parentNode: string | null;
    position: string;
    draggable: boolean;
    targetPosition: string | null;
    sourcePosition: string | null;
    dragging: boolean | null;
    selectable: boolean | null;
    connectable: boolean | null;
    dragHandle: string | null;
    extent: string | null;
    expandParent: boolean | null;
    positionAbsolute: string | null;
}, {
    height?: number | null | undefined;
    width?: number | null | undefined;
    childNodes?: {
        height?: number | null | undefined;
        width?: number | null | undefined;
        sourceEdges?: {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }[] | undefined;
        targetEdges?: {
            data: string | null;
            source: string;
            target: string;
            markerStart: string;
            markerEnd: string;
            type: string | null;
            sourceHandle: string | null;
            targetHandle: string | null;
            label: string | null;
            labelStyle: string | null;
            labelShowBg: boolean | null;
            labelBgStyle: string | null;
            labelBgPadding: string | null;
            labelBgBorderRadius: number | null;
            style: string | null;
            animated: boolean | null;
            hidden: boolean | null;
            deletable: boolean | null;
            focusable: boolean | null;
            className: string | null;
            sourceNode: string | null;
            targetNode: string | null;
            selected: boolean | null;
            zIndex: number | null;
            ariaLabel: string | null;
            interactionWidth: number | null;
            id: string;
        }[] | undefined;
        data: string;
        type: string | null;
        style: string | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        id: string;
        internReferenceId: string;
        versionId: number;
        leadloversId: number | null;
        parentNode: string | null;
        position: string;
        draggable: boolean;
        targetPosition: string | null;
        sourcePosition: string | null;
        dragging: boolean | null;
        selectable: boolean | null;
        connectable: boolean | null;
        dragHandle: string | null;
        extent: string | null;
        expandParent: boolean | null;
        positionAbsolute: string | null;
    }[] | undefined;
    edges?: {
        data: string | null;
        source: string;
        target: string;
        markerStart: string;
        markerEnd: string;
        type: string | null;
        sourceHandle: string | null;
        targetHandle: string | null;
        label: string | null;
        labelStyle: string | null;
        labelShowBg: boolean | null;
        labelBgStyle: string | null;
        labelBgPadding: string | null;
        labelBgBorderRadius: number | null;
        style: string | null;
        animated: boolean | null;
        hidden: boolean | null;
        deletable: boolean | null;
        focusable: boolean | null;
        className: string | null;
        sourceNode: string | null;
        targetNode: string | null;
        selected: boolean | null;
        zIndex: number | null;
        ariaLabel: string | null;
        interactionWidth: number | null;
        id: string;
    }[] | undefined;
    data: string;
    type: string | null;
    style: string | null;
    hidden: boolean | null;
    deletable: boolean | null;
    focusable: boolean | null;
    className: string | null;
    selected: boolean | null;
    zIndex: number | null;
    ariaLabel: string | null;
    id: string;
    internReferenceId: string;
    versionId: number;
    leadloversId: number | null;
    parentNode: string | null;
    position: string;
    draggable: boolean;
    targetPosition: string | null;
    sourcePosition: string | null;
    dragging: boolean | null;
    selectable: boolean | null;
    connectable: boolean | null;
    dragHandle: string | null;
    extent: string | null;
    expandParent: boolean | null;
    positionAbsolute: string | null;
}>;
export type ChildNodeDbOutputDTO = z.infer<typeof ChildNodeDbOutputSchema>;
export type NodeDbOutputDTO = z.infer<typeof NodeDbOutputSchema>;
export {};
